# JMeter Status service config

title = "service config"

# fetch data to where
datapath = "../web/data/" # default "../web/data/", must end by "/"
# fetch default max rows
rows = 24

# mysql config
[mysql]
dsn = "user:password@tcp(localhost:3306)/dbname?parseTime=true"  # parseTime=true need to be retained

# notification config
[notification]
    should_notify_error_num = 10 # if api error num > 10 then notify
    [notification.pagerduty]
    auth_token = "******"
    service_id = "******"
    from = "**@**.com"
    notification_title = "Weak up! Server is down."

#  array, JMeter jtl list website addresses
[[websites]]
id = 1 # must exist, unique
name = "First"
URL = "https://example.com/jmeter/" # must end by "/"

[[websites]]
id = 2 # must exist, unique
name = "Second"
URL = "https://example.com/jmeter/" # must end by "/"
auth_user = "test" # for 401 Authentication
auth_password = "test"  # for 401 Authentication